### ISSUE TITLE
debug=Falseで画像表示されない

### ISSUE THREAD

**Issue by ishii-miki** [TachikawaAkebonochoClub/gekokujo#17]

**Comment by ishii-miki** [comment]
リバプロで、 https://xxxxxxx/xxxxx にきたリクエストは 静的ファイルとしてリバプロでコンテンツを応答するように対応

**Comment by tac-ichiro** [comment]
外部からは、https://gekokujyo.castle.gq/ で来ますので、其のように読み替えて対応します。

首里城の `/var/local/docker/gekokujyo` にgit clone する前提で設定しておきます
## caddy 
###  Caddyfile
```json
https://gekokujyo.castle.gq {
        tls /tls/fullchain.pem /tls/privkey.pem

    handle_path /static/* {
        root * /gekokujyo/static
        file_server browse
    }
```
### docker-compose
```yaml
version: "3.7"
services:
  caddy:
   [...]
    volumes:
      [...]
      - /var/local/docker/gekokujyo/static:/gekokujyo/static/:ro
```
